### ISSUE TITLE
TODO for improving performance

### ISSUE THREAD

**Issue by TatianaJin** [TatianaJin/circinus#14]
Listed by priority in descending order: (subject to update)

- [x] Filters for candidates (use STOA methods)
- [x] Dynamic cover
- [ ] Sample execution for estimating dynamic cover costs
- [ ] Reuse of intersection results (consider sorting/hashing of `CompressedSubgraphs` by parent vertices, as well as intersection cache)
- [ ] Use and implementation of `intersect`
   - Consider using GPU
