### ISSUE TITLE
TODO for profiling

### ISSUE THREAD

**Issue by TatianaJin** [TatianaJin/circinus#15]
- [x] to implement a `profile` mode which is non-intrusive to the existing `execute` mode
- [x] to profile query time spent on each expand operator
- [x] to profile the processed number of `CompressedSubgraphs` in each expand operator
- [x] to profile the intersection call count
- [x] to profile the intersection cost in terms of sizes of intersected sets
- [x] to calculate the number of distinct `intersect` calls for showing the ideal no-redundancy case.
